// AUTO-GENERATED by scripts/extract-non-bookable.py
// Source: docs/Client Returned/MADE Med Spa Services.xlsx (Bookable Online column).
// Do not edit by hand — re-run the script when Karlyne updates the sheet.
//
// 55 entries.

export const NON_BOOKABLE_SERVICE_NAMES: readonly string[] = [
  "Botox", // NEUROTOXINS
  "Xeomin", // NEUROTOXINS
  "Special Event Tox", // NEUROTOXINS
  "Jeuveau", // NEUROTOXINS
  "Upneeq", // NEUROTOXINS
  "Juvederm Volux", // DERMAL FILLERS
  "Restylane L", // DERMAL FILLERS
  "Restylane Lyft", // DERMAL FILLERS
  "Restylane Defyne", // DERMAL FILLERS
  "Restylane Refyne", // DERMAL FILLERS
  "Restylane Contour", // DERMAL FILLERS
  "Restylane Eyelight", // DERMAL FILLERS
  "Kysse", // DERMAL FILLERS
  "Belotero", // DERMAL FILLERS
  "Radiesse", // DERMAL FILLERS
  "Sculptra", // DERMAL FILLERS
  "Revanesse LIPS", // DERMAL FILLERS
  "Revanesse Versa", // DERMAL FILLERS
  "Kybella", // DERMAL FILLERS
  "Hyaluronidase – Small Area", // DERMAL FILLERS
  "Hyaluronidase – Medium Area", // DERMAL FILLERS
  "Hyaluronidase – Large Area", // DERMAL FILLERS
  "PCDC", // DERMAL FILLERS
  "EZ Gel – 2nd Session", // PRP / PRF
  "PRP / PRF Add-On", // PRP / PRF
  "Hydra Booster – Britenol", // FACIALS & SKIN
  "Hydra Booster – Dermabuilder", // FACIALS & SKIN
  "Hydra Booster – Growth Factor", // FACIALS & SKIN
  "Perfect Derma Peel", // CHEMICAL PEELS
  "Perfect Derma Peel Plus Booster", // CHEMICAL PEELS
  "Lightening Forte – Lactic Peel", // CHEMICAL PEELS
  "Wrinkle Forte – Glycolic Peel", // CHEMICAL PEELS
  "1L Drip Bag Add-On", // IV HYDRATION & WELLNESS
  "EBOO Ozone Therapy", // IV HYDRATION & WELLNESS
  "Semaglutide", // WEIGHT MANAGEMENT
  "Melasma Prescription Protocol", // DERMATOLOGY
  "Prescription-Strength Tretinoin Program", // DERMATOLOGY
  "Custom Compounded Skincare", // DERMATOLOGY
  "Prescription Hair Loss Treatment", // DERMATOLOGY
  "NeoClear – Acne Series of 4", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoClear – Acne Series of 6", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoSkin – Rejuvenation Series of 3", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoSkin – Rejuvenation Series of 6", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoSkin – Melasma Series of 4", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoSkin – Melasma Series of 6", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoSkin – Rosacea Series of 3", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoSkin – Spot Vascular (per area)", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoGenesis – Series of 3", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoGenesis – Series of 6", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoGenesis – Add-On to Any Appointment", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "Aerolase Neo Elite + Sylfirm X RF Microneedling (Face)", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "Aerolase Neo Elite + SkinPen + PRP (Face)", // AEROLASE NEO ELITE — NEOCLEAR / NEOSKIN / NEOGENESIS
  "NeoHair – Series of 6 (Small Area)", // AEROLASE NEO ELITE — NEOHAIR LASER HAIR REMOVAL
  "NeoHair – Series of 6 (Medium Area)", // AEROLASE NEO ELITE — NEOHAIR LASER HAIR REMOVAL
  "NeoHair – Series of 6 (Large Area)", // AEROLASE NEO ELITE — NEOHAIR LASER HAIR REMOVAL
] as const;
