#!/usr/bin/env python3
"""
Extract non-bookable services from MADE Med Spa Services.xlsx into the
TypeScript module the Convex bulk-hide mutation imports.

Re-run any time Karlyne updates the spreadsheet's Bookable Online column.

Usage (from repo root):
    python scripts/extract-non-bookable.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import openpyxl

REPO = Path(__file__).resolve().parent.parent
XLSX = REPO / "docs" / "Client Returned" / "MADE Med Spa Services.xlsx"
JSON_OUT = REPO / "docs" / "Client Returned" / "non-bookable-services.json"
TS_OUT = REPO / "convex" / "data" / "nonBookableServices.ts"


def main() -> int:
    if not XLSX.exists():
        print(f"ERROR: {XLSX} not found", file=sys.stderr)
        return 1

    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb[wb.sheetnames[0]]

    non_bookable: list[dict[str, str]] = []
    section: str | None = None
    for row in ws.iter_rows(values_only=True):
        cells = [(c if c is None else str(c).strip()) for c in row[:6]]
        name = cells[0] or ""
        is_section = (
            name
            and name == name.upper()
            and len(name) >= 4
            and not any(cells[1:])
        )
        if is_section and "COMPLETE" not in name:
            section = name
            continue
        if not name or name == "Service Name" or section is None:
            continue
        bookable_cell = (cells[5] or "").lower()
        is_bookable = "yes" in bookable_cell or "✓" in bookable_cell
        if not is_bookable:
            non_bookable.append({"section": section, "name": name})

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(non_bookable, indent=2, ensure_ascii=False), encoding="utf-8")

    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by scripts/extract-non-bookable.py",
        "// Source: docs/Client Returned/MADE Med Spa Services.xlsx (Bookable Online column).",
        "// Do not edit by hand — re-run the script when Karlyne updates the sheet.",
        "//",
        f"// {len(non_bookable)} entries.",
        "",
        "export const NON_BOOKABLE_SERVICE_NAMES: readonly string[] = [",
    ]
    for entry in non_bookable:
        ts_safe = entry["name"].replace("\\", "\\\\").replace('"', '\\"').rstrip()
        section = entry["section"]
        lines.append(f'  "{ts_safe}", // {section}')
    lines.append("] as const;")
    TS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {len(non_bookable)} entries to:")
    print(f"  {JSON_OUT.relative_to(REPO)}")
    print(f"  {TS_OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
